### ISSUE TITLE
Plugin tries to checkout to root filesystem when downloading from SVN repo

### ISSUE THREAD

**Issue by eddgrant** [adedayo/zapper#2]
Hi,

I'm trying to use the ZAP Jenkins plugin on an Ubuntu host, it seems to want to check out from the ZAP svn repository to the root filesystem `/` which cannot typically be written to by a non-superuser:

```
About to checkout or update ZAP from http://zaproxy.googlecode.com/svn/tags/2.3.0.1/2.3/
SVN error:
svn: E204899: Unable to make directories
java.io.FileNotFoundException: /zapSource/build/build.xml (No such file or directory)
  at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:299)
  at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:177)
  at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
  at org.jenkinsci.plugins.zapper.ZapRunner.perform(ZapRunner.java:98)
  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
  at hudson.model.Build$BuildExecution.build(Build.java:198)
  at hudson.model.Build$BuildExecution.doRun(Build.java:159)
  at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
  at hudson.model.Run.execute(Run.java:1706)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:88)
  at hudson.model.Executor.run(Executor.java:232)
Caused by: java.io.FileNotFoundException: /zapSource/build/build.xml (No such file or directory)
  at java.io.FileInputStream.open(Native Method)
  at java.io.FileInputStream.<init>(FileInputStream.java:146)
  at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:249)
  ... 12 more
Build step 'Run OWASP ZAP' marked build as failure
```

I can't find a configuration option in the plugin to specify where to download to, also looking at the [source code ZapRunner](https://github.com/jenkinsci/zapper-plugin/blob/master/src/main/java/org/jenkinsci/plugins/zapper/ZapRunner.java#L83) it looks like the `zapSource` folder is intended to be created in the current directory (which I presume has been assumed to be the project workspace?) hence wondering if this is a bug?

Many thanks,

Edd

**Comment by adedayo** [comment]
Thank you Edd. Apologies for the very slow response. I shall investigate this. The current directory is expected to be within the project workspace.
 
Kind regards,
Dayo

**Comment by adedayo** [comment]
Ed,

 You'd be pleased to know that I've added support for specify destination directory for the ZAP source checkouts.

 I suspect your instance was running as root, but that is besides the point.

Kind regards,
Dayo

**Comment by eddgrant** [comment]
Hey,

Thanks for this. I wondered about having run as root when I saw the path,
however when I checked I found it to be running as the Jenkins user. I
didn't dig terribly deep in to the issue though so I'm not sure why that
path was being used. However given that you've added support to specify the
checkout directory then that resolves the issue irrespective of user, as
you say.

Many thanks!

Edd

**Comment by adedayo** [comment]
Thanks Edd!
